import 'package:flutter_bloc/flutter_bloc.dart';
import '../../domain/entities/clinical_context.dart';
import '../../domain/repositories/context_repository.dart';
import 'context_event.dart';
import 'context_state.dart';

class ContextBloc extends Bloc<ContextEvent, ContextState> {
  final ContextRepository repository;

  ContextBloc({required this.repository}) : super(ContextInitial()) {
    on<LoadContexts>(_onLoadContexts);
    on<CreateContextEvent>(_onCreateContext);
    on<DeleteContextEvent>(_onDeleteContext);
  }

  Future<void> _onLoadContexts(
    LoadContexts event,
    Emitter<ContextState> emit,
  ) async {
    emit(ContextLoading());
    final result = await repository.getContextsForPatient(event.patientId);
    result.fold(
      (failure) => emit(ContextError(failure.message)),
      (contexts) => emit(ContextLoaded(contexts)),
    );
  }

  Future<void> _onCreateContext(
    CreateContextEvent event,
    Emitter<ContextState> emit,
  ) async {
    emit(ContextLoading());
    final newContext = ClinicalContext(
      id: '', // Generated by backend
      patientId: event.patientId,
      name: event.name,
      description: event.description,
      type: event.type,
      createdBy: '', // Handled by backend/auth
      createdAt: DateTime.now(),
    );

    final result = await repository.createContext(newContext);
    
    result.fold(
      (failure) => emit(ContextError(failure.message)),
      (_) {
        // Emit success then reload
        emit(const ContextOperationSuccess('Contexto creado exitosamente'));
        add(LoadContexts(event.patientId));
      },
    );
  }

  Future<void> _onDeleteContext(
    DeleteContextEvent event,
    Emitter<ContextState> emit,
  ) async {
    emit(ContextLoading());
    final result = await repository.deleteContext(event.id);
    result.fold(
      (failure) => emit(ContextError(failure.message)),
      (_) {
        emit(const ContextOperationSuccess('Contexto eliminado'));
        add(LoadContexts(event.patientId));
      },
    );
  }
}
